# https://www.appveyor.com/docs/appveyor-yml/
skip_commits:
  # do not run for testing new Linux builds
  message: /Testing new linux/

# https://www.appveyor.com/docs/lang/nodejs-iojs/
# Test against the latest version of this Node.js version
environment:
  nodejs_version: "12"

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version
  # Output useful info for debugging.
  # we should be using NPM v6+
  - node --version
  - npm --version
  - npm i -g @cypress/commit-message-install @bahmutov/print-env
  - print-env APPVEYOR
  - commit-message-install --else "npm ci"

cache:
  # cache NPM packages and Cypress binary
  # and invalidate the cache when package.json file changes
  # https://www.appveyor.com/docs/build-cache/
  - '%AppData%\npm -> package.json'
  - '%USERPROFILE%\AppData\Local\Cypress\Cache -> package.json'

# Post-install test scripts.
test_script:
  - npm run lint
  # only run if there is commit message
  # with new version
  - run-if npm run cy:version
  - run-if npm run cy:verify
  - run-if npm run cy:info
  - run-if npm run cy:cache:list

  # noticed really slow execution of some specs on Windows
  # leading to failures. Trying to increase the command timeout
  # maybe it will solve it
  - setx CYPRESS_defaultCommandTimeout 20000
  - run-if npm run test:ci:record:chrome
  - run-if npm run test:ci:record
  - run-if npm run test:ci:record:firefox
  - run-if npm run test:ci:record:edge

# Don't actually build.
build: off
