on: [push]
name: Code analysis

jobs:
  test:
    runs-on: ubuntu-18.04
    name: check tests
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: testomatio/check-tests@stable
      with:
        framework: cypress
        tests: "./cypress/integration/examples/**.spec.js"
        token: ${{ secrets.GITHUB_TOKEN }}
        has-tests-label: true
