on: [push]
name: Code analysis

jobs:
  cypress:
    runs-on: ubuntu-latest
    container:
      image: saucelabs/stt-cypress-mocha-node:v0.1.19

    steps:
      # appears that checkout@v2 uses javascript which is not compatible 
      # with the included node version in the container image.
      - name: Checkout Code
        uses: actions/checkout@v1
        
      - name: Workaround for container permissions
        run: sudo chown -R $USER:$(id -gn $USER) /github/home
      
      - name: Workaround for container folder
        run: sudo ln -s /home/seluser/.cache /github/home/.cache

      - name: Run Sauce Pipeline Test
        run: |
          saucectl run -c ./.sauce/config.yml
        env:
          BUILD_ID: ${{ github.run_id }}
          BUILD_ENV: GitHub Actions
  test:
    runs-on: ubuntu-16.04
    name: check tests
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: testomatio/check-tests@stable
      with:
        framework: cypress
        tests: "./cypress/integration/examples/**.spec.js"
        token: ${{ secrets.GITHUB_TOKEN }}
        has-tests-label: true
